
<?php

    $this->headTitle()->setSeparator(' - ');

    $this->headTitle('Тестовое задание');

    // Выводим doctype, который считывается из application.ini
    echo $this->doctype();
?>

<!doctype html>

<head>
    <?php
         //echo $this->headMeta();
    ?>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <?php
        // Выводим заголовок сайта
        echo $this->headTitle();
    ?>
    <?php

        echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/site.css');
    ?>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
</head>

<body>
<div id="content">
    <div class="text-center">
    <h1>
       <?php
            // Выводим заголовок странице, который будем формировать в каждом view
            echo $this->escape($this->title);
        ?>
    </h1>
    </div>

    <ul class="nav nav-tabs">
        <li class="nav-item">
            <a class="nav-link active" href="<?php echo $this->url(array('controller'=>'parser','action'=>'index'));?>">Главная</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="<?php echo $this->url(array('controller'=>'parser','action'=>'show'));?>">История парсинга</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#">Настройка парсинга</a>
        </li>
    </ul>

    <?php
            echo $this->layout()->content;
        ?>
</div>
</body>
</html>

