<div id="view-content">
<?php
    $this->title = "История парсинга";
    $this->headTitle($this->title);
?>
<div id = "getStateList" class="getStateList">
    <table class="table table-success">
        <thead>
        <tr>
            <th scope="col">id</th>
            <th scope="col">Доменное имя</th>
            <th scope="col">Ключевое слово</th>
            <th scope="col">Позиция в Google</th>
            <th scope="col">Дата выборки</th>
        </tr>
        </thead>
        <tbody >
            <?php
                if (count($this->paginator)){
                    // Создаём patrialLoop, передав массив фильмов, полученных от контроллера
                    echo $this->partialLoop('partials/parser.phtml', $this->paginator);
                }
            ?>
        </tbody>
    </table>
    <?= $this->paginationControl($this->paginator, 'Sliding', 'partials/my_pagination.phtml'); ?>
</div>
</div>
<div id = "res"></div>
<script>
     jQuery(document).ready(function(){
            $('.paginationControl a').unbind('click');
            $('.paginationControl a').click(function(event){
                event.preventDefault();
                var url = jQuery(this).attr('href');
                getStateList(url);
            });
     });
     function getStateList(url){
            jQuery.ajax({
                url: url,
                type: 'GET',
                dataType: 'html',
                data: {},
                success: function(data){
                    $('#getStateList').html(data);
                }
            });
     }
</script>

