<div id="view-content">
<?php
    $this->title = "История парсинга";
    $this->headTitle($this->title);
?>
<div id = "getStateList" class="getStateList">
    <table class="table table-success">
        <thead>
        <tr>
            <th scope="col">id</th>
            <th scope="col">Доменное имя</th>
            <th scope="col">Ключевое слово</th>
            <th scope="col">Позиция в Google</th>
            <th scope="col">Дата выборки</th>
            <th scope="col">Удаление</th>
        </tr>
        </thead>
        <tbody >
            <?php
                if (count($this->paginator)){
                    // Создаём patrialLoop, передав массив фильмов, полученных от контроллера
                    echo $this->partialLoop('partials/parser.phtml', $this->paginator);
                }
            ?>
        </tbody>
    </table>
    <?= $this->paginationControl($this->paginator, 'Sliding', 'partials/my_pagination.phtml'); ?>
</div>
</div>


<script>
    jQuery(document).ready(function(){
        if ($('form').click()){
            $('form').click(function(event){
                event.preventDefault();
                var url = $(this).attr('action');
                var id = $(this).attr('value');
                var page = $('.page').html();
                //alert(url+':'+id+':'+page);
                getStateList(url, id, page);
            });
        }
        if($('.paginationControl a').click()){
            $('.paginationControl a').click(function(event){
                event.preventDefault();
                var url = jQuery(this).attr('href');
                var page = $('.page').html();
                getStateList(url);
            });
        }
    });
    function getStateList(url, id=0, page){
        jQuery.ajax({
            url: url,
            type: 'post',
            dataType: 'html',
            data: {
                id : id,
                page : page
            },
            success: function(data){
                $('#getStateList').html(data);
            }
        });
    }
</script>